### ISSUE TITLE
Rename Xlang to Crossdock

### ISSUE THREAD

**Issue by HelloGrayson** [yarpc/crossdock#12]
I think since it's likely we'll reuse this tool for thriftrw and tchannel (once #11 lands), we might want to rename this.

Why? Because you can use this tool to do any sort of matrix testing across processes - we happen to be using it to test multi-lang libs, but you could also create test clients for entire services and use this tool to create automated integration tests for those.

Let's collect some names that captures better what this tool actually does, or a completely meaningless name that's nifty and easy to remember :)

cc @yarpc/yarpc

**Comment by HelloGrayson** [comment]
Some 2AM ideas:
- xsir - a docker appliance for running cross-service integration tests 

Ok. 1 idea.

**Comment by HelloGrayson** [comment]
- spreadsweet

**Comment by HelloGrayson** [comment]
skippy

**Comment by HelloGrayson** [comment]
On second thought, cross service integration tests might be more complicated than this can handle since services also have dependent processes, eg databases and other services - until docker compose supports recursive upping, it probably won't work.

Can you guys think of any other use cases for this outside of cross-language integration testing?

**Comment by HelloGrayson** [comment]
No takers? Ok - we'll stick with the name xlang for now.

**Comment by kriskowal** [comment]
- matrun (pronounced matron, portmanteau of matrix runner)
- matifest (as in ship’s manifest)
- crossdock (like cross-talk / cross product) (could use _AXIS env suffix, e.g., SERVER_AXIS)

**Comment by HelloGrayson** [comment]
I reopened this because myself and @kriskowal like the name `crossdock`.

Everyone ok with changing the name to that? @yarpc/yarpc

**Comment by kriskowal** [comment]
See #22

**Comment by abhinav** [comment]
I'm okay with the name change.

**Comment by jc-fireball** [comment]
I am fine with the name change.

**Comment by HelloGrayson** [comment]
Resolved in #22
