### ISSUE TITLE
Allow clients to pass, skip, & fail

### ISSUE THREAD

**Issue by HelloGrayson** [yarpc/crossdock#29]
I need to tighten the interaction between crossdock and clients in order to fail the test suite or not.

Here's my initial thoughts:

Basic Interaction
1. `HEAD` requests will be issued to all `CROSSDOCK_CLIENTS` for `CROSSDOCK_MAX_START_WAIT` seconds (default 10) - if all clients do not respond with a `200`, then the test suite will not run.
2. Tests will be issued to `/` with every combination of `CROSSDOCK_AXIS_*` as query params.
3. Tests that take longer than `CROSSDOCK_TEST_TIMEOUT` seconds (default 5) will fail. The test suite will continue to the next test, and the overall test run will report `-1` exit code.
4. Tests that return non `200` responses will fail. The test suite will continue to the next test, and the overall test run will report `-1` exit code.
5. Test suites that return a `200` will be subject to the following body:
### `200` response body

Passed

```
[{
    "status": "passed",
    "output": "Server said: akb48",
}]
```

Failed (overall test will fail if one is present)

```
[{
    "status": "failed",
    "output": "Expected: sup, Got: holler",
}]
```

Skipped (does not fail overall test, but total will be outputted)

```
[{
    "status": "skipped",
    "output": "something useful here...",
}]
```

Unparseable (will fail the overall test suite if one is present)

```
ok - i'm not using the agreed format
```

@yarpc/yarpc

**Comment by HelloGrayson** [comment]
The only thing I might change is that results are always returned in a list, for example:

```
[
    {"status": "passed", "output": "Server said: ..."},
]
```

This would let the test client run arbitrary test cases within the context of a single test case - which will be useful when the dimensions provided by `CROSSDOCK_AXIS_*` vary by test case.

Perhaps crossdock can detect if its a list or not...

**Comment by kriskowal** [comment]
Let’s start with the array of results. Maybe we can also report the "behavior" and "server" properties, so we can jq through the results.

**Comment by HelloGrayson** [comment]
@kriskowal nice - good idea :)

**Comment by jc-fireball** [comment]
+1

**Comment by abhinav** [comment]
Sounds good.

**Comment by HelloGrayson** [comment]
This is now on master
