### ISSUE TITLE
Relying on $TRAVIS_BRANCH is causing us to overwrite *:latest containers in Docker Hub

### ISSUE THREAD

**Issue by HelloGrayson** [yarpc/crossdock#31]
Turns out the `$TRAVIS_BRANCH` environment variable acts in a bit of a surprising way:

> For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).

To be specific, this means that the value of `$TRAVIS_BRANCH` looks like this:

```
continuous-integration/travis-ci/push - $TRAVIS_BRANCH=<current branch name>  
continuous-integration/travis-ci/pr - $TRAVIS_BRANCH=master  
```

Since our `after_success` target uses `$TRAVIS_BRANCH` to tag our Docker Container and then [pushes it to Docker Hub](https://hub.docker.com/r/yarpc/crossdock/tags/), it means that EVERY PR is overwriting the `latest` tag in Docker Hub. 

This means that any breaking changes in a PR will overwrite master, causing every repo's test to fail.

**Comment by breerly** [comment]
This is blocking https://github.com/yarpc/yarpc-java/pull/42

**Comment by breerly** [comment]
And probably any other builds

**Comment by breerly** [comment]
My guess is that I either didn't bash correctly, or I'm misunderstanding how "latest" works in Docker Hub.

**Comment by breerly** [comment]
Hmmm - the following link seems to indicate that latest is not overwritten unless either no tag is set or latest is set: https://stackoverflow.com/questions/27643017/do-i-need-to-manually-tag-latest-when-pushing-to-docker-public-repository

**Comment by breerly** [comment]
Found the culprit:

```
TRAVIS_BRANCH:For builds not triggered by a pull request this is the name of the branch currently being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the pull request (in many cases this will be master).
```

**Comment by HelloGrayson** [comment]
Solved and blogged - https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/#thetravisymlrecipe

**Comment by HelloGrayson** [comment]
Looks like these guys could use this - https://github.com/diagrams/diagrams-travis/pull/1#issuecomment-191506094
