### ISSUE TITLE
Port crossdock integration code from yarpc-go

### ISSUE THREAD

**Issue by abhinav** [yarpc/crossdock#47]
The code in https://github.com/yarpc/yarpc-go/tree/master/crossdock/client/behavior is for integrating with crossdock, allowing writing behaviors similar to a test framework. I think we should port that to a subpackage of this repo. This will allow yarpc-go and other cross-lang testing packages for Go to depend on just crossdock to get all the additional functionality.

**Comment by yurishkuro** [comment]
+1

**Comment by HelloGrayson** [comment]
I'm squatting on github.com/crossdock so that we can have client libs and docs all living in the same org. For the Go lib, we can move it into here for now, but I'll want to move to the org before going generally available.

**Comment by abhinav** [comment]
This is done now https://github.com/crossdock/crossdock-go
