### ISSUE TITLE
Error code seems inconsistent

### ISSUE THREAD

**Issue by yurishkuro** [yarpc/crossdock#76]
I am running crossdock from the following makefile target:

``` make
.PHONY: crossdock
crossdock:
    docker-compose -f $(XDOCK_YAML) kill python
    docker-compose -f $(XDOCK_YAML) rm -f python
    docker-compose -f $(XDOCK_YAML) build python
    docker-compose -f $(XDOCK_YAML) run crossdock 2>&1 | tee run-crossdock.log
    grep 'Tests passed!' run-crossdock.log
```

It sometimes exits with an error code, even though the output states all tests were successful:

```
352/352 passed (0/352 skipped)

Tests passed!

make: *** [crossdock] Error 1
```

The grep command is not even executed.

**Comment by bombela** [comment]
It might be that you are getting a non 0 return code from tee. Make will
exit a rule at the first error. You could prefix the "docker run crossdock"
by @ to ignore errors, as it looks like you are using grep for checking the
status.

**Comment by yurishkuro** [comment]
You might be right. Actually the reason I had the tee was because crossdock used to not return an error on failures. I'll remove it.

BTW, I don't think `@` in the makefile makes the command status ignored, it just doesn't print the command. But this would work:

``` shell
sh -c 'docker-compose -f $(XDOCK_YAML) run crossdock 2>&1 | tee run-crossdock.log' || true
```

**Comment by bombela** [comment]
you are right @ is to hide the command echo. Its "-" that ignores the
return code. But crossdock should be returning an error code properly so
you only need to to end your rule with "docker-compose -f $(XDOCK_YAML) run
crossdock".
