### ISSUE TITLE
Filtering/pruning of axis per behavior

### ISSUE THREAD

**Issue by vivekrsharma** [yarpc/crossdock#82]
Currently we take a complete cross product of each axis per
behavior. However we need to filter behavior in scenarios
where we want a particular axis values to not be executed.
Consider the example below:
  AXIS_SERVER=go,java,python,node
  AXIS_CLIENT=go,java,python,node
  AXIS_TRANSPORT=tchannel,http

  BEHAVIOR_RAW=server,client,transport

  Right now, there's no way to skip java for tchannel transport.

Proposed solutions
Solution # 1
  We introduce a new separator that will be used to prune the list.
  BEHAVIOR_RAW=server,client,transport-java

Solution # 2
  We introduce a new behavior along with the behavior that would
represent the axis that you don't want to have.
  AXIS_SERVER_SKIP=java
  AXIS_CLIENT_SKIP=go,java,python,node
  AXIS_TRANSPORT_SKIP=tchannel
  BEHAVIOR_RAW_SKIP=server_skip,client_skip,transport_skip

**Comment by bombela** [comment]
What about:

```
AXIS_SERVER=go,java,python,node
AXIS_CLIENT=go,java,python,node
AXIS_TRANSPORT=tchannel,http

BEHAVIOR_RAW=server,client,transport
BEHAVIOR_RAW_SKIP=server=java+transport=tchannel,client=go+server=java
```

`BEHAVIOR_*_SKIP` format is a coma separated list of filters. A filter is a concatenated list (via `+`) of axis value equality test.  In my example above:

If the axis server equals to "java" and the axis transports equals "tchannel", then the behavior combination is skipped. Similarly if the client is go and the server is java, the combination is skipped.

The format is easy to parse: split on `,` to get every rules. Split on `+` to get every conditions. Split on `=` to get the axis and value to compare to.

Yield an error if any given axis and value thereof is invalid. Before running a behavior combination, test every skip conditions. If one matches, skip the behavior.

**Comment by vivekrsharma** [comment]
According to latest suggestion from @kriskowal -

SKIP_RAW=server:java+transport:tchannel,client:go+server:java is the way we will deal with pruning.
